### ISSUE TITLE
Contact Page - Can you please centre the text on this page to follow the design

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/De-Sena-Law-2016#2]

**Comment by melliott** [comment]
Now centered. 

I didn't include the facebook link in the banner image. Morris and I discussed it and thought it was inconsistent with the rest of the page designs. Did you want it it the main content instead?

**Comment by tgascoigne14** [comment]
Yes, please put it with the main content. I'm okay with it not being in the
header image.  Thank you!

Tina

_Tina Gascoigne_
_Account Lead_
CCI Studios, Inc.
_Mail:_ 136 Christina St. N., Sarnia, ON N7T 5T9
_Phone:_ (519) 337-8837
_Fax:_ (519) 337-8316
_Email:_ tgascoigne@ccistudios.com
_Web:_ www.ccistudios.com

**2010, 2012 & 2013 Outstanding Business Achievement Award Recipient**

P _Please print this e-mail only if necessary_

_You have received this email because you have a business relationship with
CCI Studios.  If you believe this was done in error or if you would like to
unsubscribe from any future digital communication, please click here
http://www.ccistudios.com/unsubscribe._
