### ISSUE TITLE
iPad - Landscape - Services - Formatting issues - see screenshot

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/De-Sena-Law-2016#3]
![img_0512](https://cloud.githubusercontent.com/assets/8631079/12144856/91f3bb7a-b458-11e5-9ca9-d120eb65f5d7.png)

**Comment by melliott** [comment]
This isn't happening to me on my computer or when I tell my browser to act like an iPad. Will need an iPad to test with.

**Comment by melliott** [comment]
Looks good now
