### ISSUE TITLE
Responsive - Services - Can you please allow users to decrease service panels by clicking the arrow again.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/De-Sena-Law-2016#4]
Right now the only way to decrease a service panel is to choose another service.

**Comment by melliott** [comment]
If a user closes the only open panel, the panels section takes up 25% of the width of the page - one has to be open at all times. It will have to be that way for at least desktop.

It would be a nice feature on mobile. I would have to get Morris to look at having it behave this way just on mobile, though he would argue all the panels should be open.

**Comment by melliott** [comment]
Toggles on mobile/One is always open on desktop.
